# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samibirnbaum.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Sami Birnbaum
  avatar: avatar.png
  # gravatar: https://www.gravatar.com/avatar/fdac9cf8b3c18cf35ef94b2e6e2554ba.jpg?f=y
  description: "Sami Birnbaum's Portfolio | Projects | Case Studies | Posts | Contact | About" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Developer | Programmer | Dad.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "samibirnbaum1@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "samibirnbaum/"
  google_plus:
  instagram: 
  linkedin:  https://www.linkedin.com/in/samibirnbaum/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: https://stackoverflow.com/users/7913423/sami-birnbaum?tab=profile
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-107087291-1"
  disqus_shortname:
  search: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 20
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
    input: GFM
sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jemoji

# This comment in a post tells it what to display on home page from the post
excerpt_separator: <!--more-->
